In [1]:
import datetime as dt
import pandas as pd
import numpy as np

In [2]:
dfs = pd.read_html("https://www.skysports.com/premier-league-table", header=0)
df = pd.DataFrame(dfs[0], columns=["Team"])
df.rename(columns={"Team": "Club"}, inplace=True)

In [3]:
df.to_csv("data/premier-league-teams-{}.csv".format(dt.datetime.now().year))

In [4]:
col_types = {'Age': np.int32, 'Potential': np.int32, 'Overall': np.int32}
ff18 = pd.read_csv('data/CompleteDataset.csv', usecols=['Name', 'Nationality', 'Club', 'Photo', 'Value', 'Age', 'Wage', 'Potential', 'Overall', 'Finishing', 'Penalties', 'Aggression', 'Crossing', 'Stamina', 'Dribbling'], dtype=col_types)

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (23,40,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
ukteams = ff18[ff18.Club.isin(df.Club)]
ukteams.head(11)

,Name,Age,Photo,Nationality,Overall,Potential,Club,Value,Wage,Aggression,Crossing,Dribbling,Finishing,Penalties,Stamina
5,De Gea,26,https://cdn.sofifa.org/sm/18/players/193080.png,Spain,91,93,Manchester United,€74.5M,€295K,38,17,18,13,40,40
6,K. De Bruyne,26,https://cdn.sofifa.org/sm/18/players/192985.png,Belgium,91,92,Manchester City,€104.5M,€395K,73,92,86,83,77,88
8,E. Hazard,26,https://cdn.sofifa.org/sm/18/players/183277.png,Belgium,91,91,Chelsea,€95.5M,€405K,54,81,94,84,86,81
15,T. Courtois,25,https://cdn.sofifa.org/sm/18/players/192119.png,Belgium,89,92,Chelsea,€59M,€190K,23,14,13,14,27,38
17,David Silva,31,https://cdn.sofifa.org/sm/18/players/168542.png,Spain,89,89,Manchester City,€58.5M,€285K,55,83,87,73,73,81
18,S. Agüero,29,https://cdn.sofifa.org/sm/18/players/153079.png,Argentina,89,89,Manchester City,€66.5M,€325K,63,70,89,91,83,77
21,N. Kanté,26,https://cdn.sofifa.org/sm/18/players/215914.png,France,88,90,Chelsea,€59.5M,€245K,90,68,79,65,54,95
22,H. Kane,23,https://cdn.sofifa.org/sm/18/players/202126.png,England,88,91,Tottenham Hotspur,€76.5M,€210K,76,75,80,92,86,88
23,P. Pogba,24,https://cdn.sofifa.org/sm/18/players/195864.png,France,88,92,Manchester United,€76M,€250K,78,80,87,73,76,91
25,C. Eriksen,25,https://cdn.sofifa.org/sm/18/players/190460.png,Denmark,88,91,Tottenham Hotspur,€74.5M,€210K,46,87,84,81,67,91
27,A. Sánchez,28,https://cdn.sofifa.org/sm/18/players/184941.png,Chile,88,88,Manchester United,€60M,€325K,80,81,90,84,77,86